name: build

on:
  push:
    tags: [ '*' ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: PPA
      run: sudo apt-add-repository ppa:gnuradio/gnuradio-releases-3.9
    - name: Update
      run: sudo apt update
    - name: Install GNU Radio
      run: sudo apt -y install gnuradio gnuradio-dev liblog4cpp5-dev liblog4cpp5v5 libboost-system1.71.0 libboost-system1.71-dev libgnuradio-filter3.9.8 libgnuradio-blocks3.9.8 libgnuradio-pmt3.9.8 libgnuradio-fft3.9.8 libgnuradio-soapy3.9.8 soapysdr0.7-module-rtlsdr librtlsdr0 libsoapysdr-dev
    - name: make
      run: make
    - name: Create Release
      uses: ncipollo/release-action@v1.10.0
      with:
        allowUpdates: true
        artifacts: gr-scan
      

